### ISSUE TITLE
unit test of ARM Cortex-M firmware failed 

### ISSUE THREAD

**Issue by findo** [RiS3-Lab/DICE-DMA-Emulation#2] opened 2020-11-26 02:40 UTC
`./run.py f103 ./Firmware/Binaries-DICE/F103_ADC_SingleConversion_TriggerTimer_DMA.elf ./output` failed

```shell
/home/wangfeng/DICE-DMA-Emulation/DICE-Evaluation/ARM/Unit-Test/../DICE-P2IM-Utilities/me.py:44: DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.
  parser = configparser.SafeConfigParser()
***************
./Firmware/Binaries-DICE/F103_ADC_SingleConversion_TriggerTimer_DMA.elf
***************
Change working dir to: 1/
CWD: /home/wangfeng/DICE-DMA-Emulation/DICE-Evaluation/ARM/Unit-Test/1
cmd to launch this script: /home/wangfeng/DICE-DMA-Emulation/DICE-Evaluation/ARM/Unit-Test/../DICE-P2IM-Utilities/me.py -c mi-f103.cfg

args after processing: Namespace(afl_file=None, config='mi-f103.cfg', eval=False, gt=None, model_if=None, print_to_file=False, run_from_fs=False, run_num='1')

configurations after processing: Namespace(board='NUCLEO-F103RB', img='/home/wangfeng/DICE-DMA-Emulation/DICE-Evaluation/ARM/Unit-Test/Firmware/Binaries-DICE/F103_ADC_SingleConversion_TriggerTimer_DMA.elf', log_f='/home/wangfeng/DICE-DMA-Emulation/DICE-Evaluation/ARM/Unit-Test/me.log', mcu='STM32F103RB', objdump='/home/gym/DICE-DMA-Emulation/p2im/gcc-arm-none-eabi-9-2020-q2-update/bin/arm-none-eabi-objdump', peri_addr_range=512, qemu_bin='/home/wangfeng/DICE-DMA-Emulation/DICE-precompiled/ARM_bin/qemu-system-gnuarmeclipse', qemu_log='unimp,guest_errors,int', retry_num=3)

depth 1, stage: SR_R_ID
cmd: /home/wangfeng/DICE-DMA-Emulation/DICE-precompiled/ARM_bin/qemu-system-gnuarmeclipse -verbose -verbose -d unimp,guest_errors,int -nographic -board NUCLEO-F103RB -mcu STM32F103RB -image /home/wangfeng/DICE-DMA-Emulation/DICE-Evaluation/ARM/Unit-Test/Firmware/Binaries-DICE/F103_ADC_SingleConversion_TriggerTimer_DMA.elf -pm-stage 1 -trace trace-depth:1,stage:1.0 -reg-acc reg_acc-depth:1,stage:1.0 -model-output model-depth:1,stage:1.0.json
ret_val: 0x7f
ret_val == 0x7f, re-run it!
ret_val: 0x7f
ret_val == 0x7f, re-run it!
ret_val: 0x7f
ret_val == 0x7f, re-run it!
Traceback (most recent call last):
  File "/home/wangfeng/DICE-DMA-Emulation/DICE-Evaluation/ARM/Unit-Test/../DICE-P2IM-Utilities/me.py", line 1158, in <module>
    ret_val = stage1()
  File "/home/wangfeng/DICE-DMA-Emulation/DICE-Evaluation/ARM/Unit-Test/../DICE-P2IM-Utilities/me.py", line 358, in stage1
    ret_val = qemu_run(cmd, cfg.retry_num, stage)
  File "/home/wangfeng/DICE-DMA-Emulation/DICE-Evaluation/ARM/Unit-Test/../DICE-P2IM-Utilities/me.py", line 192, in qemu_run
    color_print(error_rv[stage][ret_val], "red")
KeyError: 1
['/home/wangfeng/DICE-DMA-Emulation/DICE-precompiled/ARM_bin/qemu-system-gnuarmeclipse', '-verbose', '-verbose', '-d', 'unimp,guest_errors,int', '-nographic', '-board', 'NUCLEO-F103RB', '-mcu', 'STM32F103RB', '-image', '/home/wangfeng/DICE-DMA-Emulation/DICE-Evaluation/ARM/Unit-Test/Firmware/Binaries-DICE/F103_ADC_SingleConversion_TriggerTimer_DMA.elf', '-pm-stage', '1', '-trace', 'trace-depth:1,stage:1.0', '-reg-acc', 'reg_acc-depth:1,stage:1.0', '-model-output', 'model-depth:1,stage:1.0.json']

exit_callback is invoked

Execution time(seconds):
0.06402420997619629
Traceback (most recent call last):
  File "/home/wangfeng/DICE-DMA-Emulation/DICE-Evaluation/ARM/Unit-Test/../DICE-P2IM-Utilities/statFp3.py", line 261, in <module>
    aux = getStat(sys.argv[1],sys.argv[2],sys.argv[3])
  File "/home/wangfeng/DICE-DMA-Emulation/DICE-Evaluation/ARM/Unit-Test/../DICE-P2IM-Utilities/statFp3.py", line 177, in getStat
    for intrs in data["interrupts"]:
KeyError: 'interrupts'
```

**Comment by alejoseb** [comment] 2020-11-30 17:46
I cannot reproduce your issue, the scripts work without any issue. I double checked in our development environment and on clean installations of Ubuntu 16.04 and 18.04. Please verify that you follow the instructions in the README file.

**Closed as completed** 2020-12-01 01:54 UTC
Labels: invalid

**Comment by MrMatch246** [comment] 2021-10-29 11:35
Hey, i just had the same error,and i looked at the code and either im blind and stupid or u got a bug there,because for the first traceback you execute `color_print(error_rv[stage][ret_val], "red")` which is initiated with `error_rv = {2: {0x24: "Cannot find SR Model which is supposed to exist"}}` but referenced with stage = 1 therefore the key error .
Sure the cause might be that im trying to run it on ParrotOS but thats a bug anyway
